apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: global-api
  template:
    metadata:
      labels:
        app: global-api
    spec:
      containers:
      - name: global-api
        image: your_dockerhub_account/global-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "global-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "global_db"
        - name: POSTGRES_USER
          value: "global_user"
        - name: POSTGRES_PASSWORD
          value: "global_password"
        volumeMounts:
        - name: shared-storage
          mountPath: /app

      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-storage-claim
