apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-api
  template:
    metadata:
      labels:
        app: store-api
    spec:
      containers:
      - name: store-api
        image: your_dockerhub_account/store-api:latest
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_HOST
          value: "store-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "store_db"
        - name: POSTGRES_USER
          value: "store_user"
        - name: POSTGRES_PASSWORD
          value: "store_password"
